/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Reward = { 'goldStar' : null } |
  { 'bronzeStar' : null } |
  { 'silverStar' : null };
export interface UserProfile {
  'age' : [] | [bigint],
  'preferredLanguage' : string,
  'name' : string,
}
export interface UserProgress {
  'totalScore' : bigint,
  'stars' : bigint,
  'completedLessons' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Word {
  'text' : string,
  'translation' : string,
  'category' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardReward' : ActorMethod<[Principal, Reward], undefined>,
  'checkQuizAnswer' : ActorMethod<[string, string], boolean>,
  'completeLesson' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProgress' : ActorMethod<[], UserProgress>,
  'getRewards' : ActorMethod<[], Array<Reward>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[Principal], UserProgress>,
  'getUserRewards' : ActorMethod<[Principal], Array<Reward>>,
  'getWordsByCategory' : ActorMethod<[string], Array<Word>>,
  'initializeVocabulary' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];