/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Reward = IDL.Variant({
  'goldStar' : IDL.Null,
  'bronzeStar' : IDL.Null,
  'silverStar' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'preferredLanguage' : IDL.Text,
  'name' : IDL.Text,
});
export const UserProgress = IDL.Record({
  'totalScore' : IDL.Nat,
  'stars' : IDL.Nat,
  'completedLessons' : IDL.Nat,
});
export const Word = IDL.Record({
  'text' : IDL.Text,
  'translation' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardReward' : IDL.Func([IDL.Principal, Reward], [], []),
  'checkQuizAnswer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'completeLesson' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProgress' : IDL.Func([], [UserProgress], ['query']),
  'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
  'getUserRewards' : IDL.Func([IDL.Principal], [IDL.Vec(Reward)], ['query']),
  'getWordsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Word)], ['query']),
  'initializeVocabulary' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Reward = IDL.Variant({
    'goldStar' : IDL.Null,
    'bronzeStar' : IDL.Null,
    'silverStar' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'preferredLanguage' : IDL.Text,
    'name' : IDL.Text,
  });
  const UserProgress = IDL.Record({
    'totalScore' : IDL.Nat,
    'stars' : IDL.Nat,
    'completedLessons' : IDL.Nat,
  });
  const Word = IDL.Record({
    'text' : IDL.Text,
    'translation' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardReward' : IDL.Func([IDL.Principal, Reward], [], []),
    'checkQuizAnswer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'completeLesson' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProgress' : IDL.Func([], [UserProgress], ['query']),
    'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
    'getUserRewards' : IDL.Func([IDL.Principal], [IDL.Vec(Reward)], ['query']),
    'getWordsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Word)], ['query']),
    'initializeVocabulary' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };